name: quizzler
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  http_requests: ^1.4.0
  html: ^0.15.0


  cupertino_icons: ^0.1.2
  #TODO: Step 1 - Add the rFlutter Alert package as a dependency here and use "Packages get".
  rflutter_alert: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

